HISTORY.rst
schematics/__init__.py
schematics/models.py

- Fixes #279.
- Use x.y.z as said per https://github.com/schematics/schematics/pull/273

Release 1.0.2

---

setup.py
tests/test_mongo.py
tests/test_temporal.py
tox.ini

I started using Schematics on a project today, and was surprised to see my app immediately exit with `ImportError: No module named six`. It looks like commit 0782c36eeb1232c45fa678c0aa548ca96e96b356 started using [six][six] in Schematics, but it was never added to `install_requires` in `setup.py`.
This is not currently caught in Travis because tests install python-coveralls, which [itself requires six][cover-six]. So, this pull request (1) add a requirement for six, and (2) adds new Tox environments that will run unit tests with only `py.test` additionally installed to catch this kind of error.
[six]: https://pypi.python.org/pypi/six
[cover-six]: https://github.com/z4r/python-coveralls/blob/dc05431c7c3d30ba6c7ce486421240a062e47e68/requirements.txt#L4

Add missing requirement for `six`

---

schematics/types/base.py
tests/test_types.py

It's better to check `choices` type, because string is also a valid option.

Type choices should be list or tuple

---

schematics/models.py
schematics/transforms.py
tests/test_ordered_serialization.py

I have implemented simple way of declaring order of fields in serialized output. 
Something like this does not have great technical value, but it is nice to return dictionary always in the same format when using schematics as validation layer for REST API (which is the way that I am using it).
This might not be the best way to implement this, but it reflects just the thing that I need. 
I was not sure what to do with fields that are not specified in `fields_order` list, so I did nothing and in that case order of fields is not guaranteed in any way, just as it is not guaranteed with `dict` (well, fields that are mentioned in `fields_order` will be pushed back, other fields will be left in front, but that is just a side effect).
What do you think?
I am opened to suggestions, if you have …

Support for fields order in serialized format via Options class in model

---

schematics/exceptions.py
schematics/transforms.py
tests/test_models.py

Schematics already has excellent separation of data parsing and validation. This PR adds the ability to access the result of converting primitive data in case of ModelConversionError.
`import_loop` is the central mechanism for converting primitive values to native Python objects. If it encounters a conversion error when working on one field, the `import_loop` catches and stores and the error and moves on to the next field instead of bailing out completely on the first error. By the end of the `import_loop`, it has all the partial data parsed based on best effort in addition to all errors encountered. However, ModelConversionError only exposes the errors. This PR makes parsing result accessible as well through ModelConversionError.
Specifically, ModelConversionError is updated to have a …

Include Partial Data when Raising ModelConversionError

---

schematics/types/base.py

The schematics DateTimeType does not yet accept timezones but implicitly takes the string as UTC. It should or could also accept date strings that explicitly state UTC by 'Z' suffix. 
Side advantage: the default format given by i.e. JavaScript's isoformat()-method (and some other ISO8601-compliant libraries that use to convert to UTC xmlschema) will be accepted out of the box.
This is a best effort approach. To handle timezones will be platform dependent, introduce dependencies (dateutils) or require additional work until strptime's %z (python 3.3 ... ) can be used. However, if you work with UTC+UTC based libraries and as the date is perceived as UTC anyway, it seems counter intuitive having to configure this every time.

accept optional 'Z' suffix for UTC date_time_type format

---

schematics/types/base.py

A very small pull request to improve the parsing error message for `DateTimeType` with custom formats.
Reason: If you build a (distributed) API with a DateTimeType you may get hard to debug errors for custom formats.

improves date_time_type error message for custom formats

---

schematics/types/base.py

For `min_value` and `max_value` the errors said 'greater than' and 'less than' but according to the code it should be 'greater than or equal to' and 'less than or equal to'.

Fix NumberType range validation messages

---

README.rst

This section of the docs references some forking history that is no longer visible on the project's page.

Removed the doc section about the project's fork.

---

setup.py

`mock` is only being used in tests.

Remove mock from install_requires

---

schematics/types/base.py

Since this is only used during validation I don't see a strong reason to compile the regex, Python will do this on the fly and it will also enable deepcopy to work which is a requirement for subclassing models.

Do not compile regex

---

schematics/types/serializable.py

Consider:
```python
class M(Model):
f = StringType()
@serializable
def s(self):
return 'foo'
```
Since `M.f == M._fields['f']`, I would expect `M.s == M._serializables['s']` to be true as well.
But accessing `M.s` currently results in `M.s()` to be evaluated as if it were a classmethod. I suspect this is not by design. Does anyone else see a reason why this should be so?

Don't evaluate serializable when accessed through class

---

schematics/models.py
tests/test_model_type.py

When a compound field is set to None, set the value
of that field to `None` instead of creating an empty `ModelType` of that
compound object.

Set `None` on a field that's a compound type should honour that semantics

---

schematics/transforms.py

In one common use case (e.g. where import_loop is called from validate.py) there is no mapping passed into import_loop, and the field_converter function doesn't even take a mapping keyword argument.
Where there is no mapping, it's probably best to skip the try branch. It will only do two useless gets which inevitably end up with an empty dict. That {} is passed into a function that will at best do nothing with it or raise a TypeError through the except branch.
I suggest going straight to a mapping-less call to field_converter if no mapping was passed into import_loop to begin with.
All unit tests pass. I've informally profiled in PyCharm, and there is a slight improvement on our (Skyscanner's) test cases.

avoid unnecessary code path through try/except

---

schematics/models.py
schematics/types/base.py
schematics/types/compound.py
tests/test_model_type.py
tests/test_polymodeltype.py

Implements the feature requested in #330.
Commit message:
ModelType fields can now be initialized with a string consisting of the name of the containing model. These will be turned into actual class references once the class has been created.

Add support for self-referential ModelType fields

---

schematics/models.py
tests/test_models.py

Currently, `del model_instance.somefield` performs
```python
del model_instance._fields['somefield']
```
But instances don't have a `_fields` member, so this results in `somefield` to be dropped not from the instance but **from the class, affecting all instances**.
This patch changes the behavior of `FieldDescriptor.__delete__` to match that of `Model.__delitem__`, which simply resets the field's value to `None`.
If manipulating `_fields` is necessary, it should be done through the class.

Fix FieldDescriptor.__delete__ to not touch model

---

schematics/transforms.py
schematics/types/compound.py

In `export_loop` functions,
* get rid of redundancies in conditionals
* when about to return `None`, do so explicitly.
Can someone with more historical knowledge please check if any of the removed code in `compound.py` was intended to do something but didn't because it was buggy?
Specifically:
1. In `ModelType.export_loop()` we had
```python
if shaped and len(shaped) == 0 and self.allow_none():
return shaped
elif shaped:
return shaped
elif print_none:
return shaped
```
All cases covered by the first conditional are covered by the second as well. But maybe the second one was supposed to read something like:
```python
elif shaped and len(shaped) > 0:
return shaped
```
But still, this would only make sense for a custom representation that's not a `dict`, yet the main `export_loop` function …

export_loop cleanup

---

schematics/transforms.py
schematics/types/compound.py
tests/test_serialize.py

This PR changes the primitive representation of empty models from `None` to `{}` (empty `dict`) so as to make a distinction between an actual `None` and an instance that has no values to export.
It depends on #350, which fixes the filtering of empty containers during export, and addresses  #235.
Diff for the relevant commit: https://github.com/schematics/schematics/commit/912afcc02c5506290d8fe5d818207c141cc6d1e3
The current behavior can lead to counterintuitive outcomes, particularly when using the `serialize_when_none` switch.
Example:
```python
class Inner(Model):
class Options:
serialize_when_none = False
l = ListType(IntType())
class Outer(Model):
m = ModelType(Inner)
```
```python
>>> instance = Outer()
>>> instance.to_primitive()
{'m': None} # as expected since instance.m hasn't …
```

Always export empty compound objects as {} / []

---

schematics/types/base.py
tests/test_validation.py

This makes fields pickleable. In addition, it allows validator methods
to override similarly named validators on parent types (previously they
would all run).
```python
class FooType(IntType):
def validate_range(self, value):
pass
```
```python
>>> field = FooType(max_value=1)
```
**Before:**
```python
>>> field.validators
[functools.partial(<function BaseType.validate_required at 0x1019d7400> ...),
functools.partial(<function BaseType.validate_choices at 0x1019d7488> ...),
functools.partial(<function NumberType.validate_is_a_number at 0x1019da0d0> ...),
functools.partial(<function NumberType.validate_range at 0x1019da158> ...),
functools.partial(<function FooType.validate_range at 0x101bc3a60> ...)]
```
```python
>>> field.validate(9)
Traceback (most recent call last):
...
... …
```

Collect field validators as bound methods

---

schematics/types/base.py
tests/test_types.py

Fixes and simplifies Unicode routines. Also adds tests which were
notably absent.
***
Python 2:
```python
>>> StringType()('\xc3\xa4').encode('utf-8')
'\xc3\xa4'
```
Python 3:
```python
>>> StringType()(b'\xc3\xa4').encode('utf-8')
Traceback (most recent call last):
...
schematics.exceptions.ConversionError: ["Couldn't interpret 'b'\\xc3\\xa4'' as string."]
```

Correctly decode bytestrings in Python 3

---

schematics/datastructures.py
schematics/models.py
schematics/transforms.py
schematics/types/base.py
schematics/types/compound.py
schematics/types/serializable.py
schematics/validate.py
tests/test_compound.py
tests/test_functional.py
tests/test_list_type.py
tests/test_model_type.py
tests/test_polymodeltype.py
tests/test_recursive_import.py
tests/test_serialize.py
tests/test_types.py
tests/test_validation.py

A rewrite of #266.
This is a huge PR, but it's split into meaningful commits, each of which represents a working state with all tests passing.
`env` is now always passed to all `to_primitive`, `to_native`, and `export_loop` methods on types. Consequently, the standard `field_converter` interface also has `env` as a mandatory component: `field_converter(field, value, env)`.
The `env` object will be set up by either `import_loop` or `export_loop` during the first iteration if the application hasn't supplied it by then.
The overloading of "context" with a number of uses has been resolved as follows:
* `context` in `import_loop()` and `validate()` renamed to `trusted_data`
* `context` as an argument to `to_native()`, `to_primitive()`, `validate()`, and `mock()` superseded by `env`
* `context` …

Propagate environment during recursive import/export/validation

---

schematics/contrib/mongo.py
schematics/models.py
schematics/types/base.py
schematics/types/compound.py
schematics/validate.py
tests/test_mongo.py
tests/test_types.py
tests/test_validation.py

Validator functions are supposed to operate on native values, so
it makes sense to perform the conversion in BaseType.validate()
as opposed to the validation loop. It is now possible to invoke
`field.validate()` directly, which is especially useful for testing.
***
See #338.
Reverses the patch introduced in #339, as it's now unnecessary, but keeps the test.

Make sure field.validate() uses a native type

---

schematics/types/base.py
tests/test_types.py

This I think is a bona fide bug:
```python
>>> IntType().to_native(2.999)
2
```
That can't be by design, right?
As an aside, what do we need `LongType` for? Even in Python 2.6 integers become longs as needed:
```python
>>> int(987358972389723895234234234897)
987358972389723895234234234897L
```

Fix NumberType.to_native()

---

schematics/common.py
schematics/models.py
schematics/transforms.py
schematics/types/base.py
schematics/types/compound.py
schematics/types/serializable.py
tests/test_compound.py
tests/test_export.py
tests/test_ordered_serialization.py
tests/test_serialize.py

This is based on the ideas I talked about [here](https://github.com/schematics/schematics/issues/337#issuecomment-157871276) and [here](https://github.com/schematics/schematics/issues/324#issuecomment-155924477). The patch standardizes on methods called `convert` and `export`:
```python
def convert(self, value, context):
```
```python
def export(self, value, format, context):
```
where `format` is either `PRIMITIVE` or `NATIVE` (or a custom format; a type could choose to support more than these two).
Compound types implement these methods directly, while basic types can just map them to `to_native` and `to_primitive` as appropriate.
The bundled compound types no longer have any concept of primitive vs. native, as it makes no difference to them.
The overhaul gets rid of the famous …

Unify import/export interface across all types

---

schematics/models.py
schematics/types/serializable.py
schematics/util.py
tests/test_binding.py

So it turns out `ModelMeta` has been giving subclasses their own copies of base class serializables, but the copies have never been invoked. The serializables have been added to the `_serializables` dict but never set as actual attributes. Lookups would therefore reach the parent class. This is now fixed.
The patch also cleans things up by eliminating most attributes on serializables. Lookups are delegated to the underlying type through `__getattr__()`. This way, the `Serializable` class doesn't have to be updated every time a new attribute is added to `BaseType`.
Finally, the type argument to the `serializable` decorator can now be either a class or an instance.

Serializable improvements

---

schematics/common.py
schematics/exceptions.py
schematics/models.py
schematics/transforms.py
schematics/types/base.py
schematics/types/compound.py
schematics/types/serializable.py
schematics/undefined.py
schematics/util.py
schematics/validate.py
tests/test_export.py
tests/test_export_level.py
tests/test_import.py
tests/test_misc.py
tests/test_models.py
tests/test_serialize.py
tests/test_validation.py

As before, objects are populated by default.
```python
class M(Model):
intfield = IntType()
stringfield = StringType()
defaultfield = StringType(default='foo')
```
```python
>>> m = M()
>>> m.to_primitive()
{'intfield': None, 'stringfield': None, 'defaultfield': 'foo'}
```
The `del` statement, which [used to be completely broken](https://github.com/schematics/schematics/pull/349), can now be used to clear an individual value.
```python
>>> del m.intfield
>>> m.to_primitive()
{'defaultfield': 'foo', 'stringfield': None}
```
Internally, we have the `Undefined` singleton as a placeholder to indicate the absence of a value.
```python
>>> m._data
{'intfield': Undefined, 'stringfield': None, 'defaultfield': 'foo'}
>>> 'intfield' in m
False
```
Attempting to access a nonexistent value through an …

Add support for undefined values

---

schematics/types/compound.py
tests/test_list_type.py
tests/test_validation.py

Currently, ListType validation error messages do not tell you WHICH item
in the list was invalid; just that one of them was. This is problematic
for showing validation errors in a UI; you typically want to show the
message next to a specific field.
I believe that a dict of item index to one or more errors (in a list) is
the most usable format for UI developers. I'm also open to returning a
list of dicts, where the position in the list matches the position in
the input; though that would often necessitate empty placeholders.
Addresses: https://github.com/schematics/schematics/issues/307
Also, fix assertions on a number of tests for validate messages:
These pytest.raises blocks stop executing when the ValidationError is
raised, meaning that any code underneath that in the block is not …

Change ListType validation messages to be a dict of index to message

---

schematics/datastructures.py
schematics/exceptions.py
schematics/models.py
schematics/transforms.py
schematics/types/base.py
schematics/types/compound.py
schematics/util.py
schematics/validate.py
tests/test_binding.py
tests/test_conversion.py
tests/test_datastructures.py
tests/test_exceptions.py
tests/test_functional.py
tests/test_list_type.py
tests/test_model_type.py
tests/test_models.py
tests/test_types.py
tests/test_validation.py

This is a refactoring of the validation/conversion machinery that aims to
* further eliminate redundant code
* make the import recursion loop more generic and reusable
* make the exception flow and error aggregation easier to understand.
It introduces some new features made possible by the redesign and a few bugfixes as well.
Since the diff is pretty big, I'm going to explain most changes below.
* Combines the validation and conversion code paths. Recursive validation of nested items and submodels is now provided by `MultiType.convert()` (formerly `to_native()`), obviating the need for parallel, validation-specific logic.
* The `validate_items()` methods on `ListType` and `DictType` are removed.
* The `validate_model()` method on `ModelType` is removed.
* Enables simultaneous conversion …

Validation refactoring + exception redesign

---

.coveragerc
schematics/models.py
schematics/transforms.py
schematics/types/base.py
schematics/types/compound.py
schematics/util.py
tox.ini

Whenever field-level conversion functions are inexpensive (as is typical), profiling indicates that the majority of time is spent in the main import/export loops. Their performance can be significantly improved with a few simple tweaks:
* Duplicate `Model._fields` as `Model._field_list` holding a native list of tuples, which is much faster to iterate over than the `OrderedDict`.
* In `atoms()`, retrieve values directly from `_data`, which is way faster than going through the class.
* Pre-build lists of trial input keys instead of computing them every time a field is encountered.
* Stop calling the redundant `wholelist()` filter as a fallback when no role is specified.
Making sure that Schematics runs on PyPy is probably more important for performance than most code optimizations, so I've …

Performance optimizations

---

.pylintrc
schematics/__init__.py
schematics/common.py
schematics/compat.py
schematics/contrib/mongo.py
schematics/datastructures.py
schematics/exceptions.py
schematics/models.py
schematics/transforms.py
schematics/types/__init__.py
schematics/types/base.py
schematics/types/compound.py
schematics/types/net.py
schematics/types/serializable.py
schematics/util.py
schematics/validate.py
setup.py
tests/test_datastructures.py
tests/test_datetime.py
tests/test_exceptions.py
tests/test_export.py
tests/test_model_type.py
tests/test_models.py
tests/test_serialize.py
tests/test_types.py
tox.ini

This set of commits standardizes on Python 3 style and replaces ad-hoc compatibility maneuvers with a shared compatibility module `compat`. It is deployed to all modules via `from .common import *`.
Changes to string handling:
* `str` now produces Unicode strings; `unicode` is obsolete.
* `unicode_literals` is now enabled; `u`-prefixes are obsolete.
On Python 2, the `__str__()` and `__repr__()` methods on `Model` and `FieldError` are patched to transparently encode non-ASCII code points.
All modules now declare `__all__` to prevent globals from leaking on `from <> import *`.
The `six` dependency is gone.

Code normalization for Python 3 + general cleanup

---

schematics/types/__init__.py
schematics/types/union.py
schematics/validate.py
tests/test_union_type.py

I've thought about PR #340 by @jmsdnns and decided to try to write a similar thing from scratch instead of adapting `PolyModelType`, since that one mostly consists of model-related machinery.
As explained in #340, saying "store value *x* with type *y*" is just not possible in the current Schematics architecture. However, as long as the type can be inferred from the value itself, it works great.
For now this thing is called `MixedType`.
```python
>>> id_field = MixedType((IntType, UUIDType))
>>> result = id_field.to_native('ee5a16cb-0ee1-46bc-ac40-fb3018b1d29b')
>>> result
UUID('ee5a16cb-0ee1-46bc-ac40-fb3018b1d29b')
>>> id_field.to_primitive(result)
'ee5a16cb-0ee1-46bc-ac40-fb3018b1d29b'
>>> id_field.to_native('99999')
99999
```
```python
numbers = ListType(MixedType((IntType, …
```

Introduce MixedType

---

schematics/types/base.py
tests/test_types.py

Hi,
Here's a pull request for the metadata/annotations feature discussed in #333
It's dead simple.  I went with the name `metadata` instead of `annotations` because I think `metadata` is more self-explanatory, and I feel that `annotations` implies strings only.

Add support for arbitrary field metadata.

---

tests/test_model_type.py

This test is to verify that a context dict, passed into model initialization, is available for use by custom data types, with the context dict keys converting to context object attributes.

Test for Model.__init__ context passing to types

---

schematics/types/base.py
tests/test_types.py

- `StringType` will reject `bool`.
- `IntType` will upcast `bool` to `int`.
***
The fact that the Python `bool` is a subclass of `int` is more a historical accident than a well-founded principle of the type system. Fundamentally, booleans have nothing to do with integers. Therefore I believe special-casing `bool` is entirely warranted.
Resolves #315.

Change conversion rules for booleans

---

schematics/models.py
schematics/transforms.py
schematics/types/compound.py
tests/test_export.py
tests/test_export_level.py
tests/test_misc.py
tests/test_serialize.py

Summary:
* `to_native()` on export now produces a dictionary again.
* The bundled converters are written as plain functions to make the code easier to understand.
Resolves #405.

Restore v1 to_native behavior; simplify converter code

---

schematics/transforms.py
schematics/types/base.py

`value in (None, Undefined)` invokes `value.__eq__`, which may have side effects.

When testing if a values is None or Undefined, use 'is'.

---

schematics/__init__.py
schematics/compat.py
schematics/contrib/machine.py
schematics/datastructures.py
schematics/deprecated.py
schematics/iteration.py
schematics/models.py
schematics/role.py
schematics/schema.py
schematics/transforms.py
schematics/types/compound.py
schematics/types/serializable.py
schematics/validate.py
tests/test_binding.py
tests/test_functional.py
tests/test_invariants.py
tests/test_models.py
tests/test_schema.py
tests/test_serialize.py
tests/test_validation.py
tox.ini

Implements #446 
This is the foundational work to get back compatibility with SQLAlchemy. To do that, the concept of Serializable setters is reintroduced, along with a lower level abstraction of the Model named Schema.
The functional API can now rely on the Schema declaration directly, which simplifies integration by exposing a smaller surface. More work will need to be done to introduce a CompoundType with pure Schema.
Additionally, the concept of data validation stages is introduced (see `contrib/machine.py`) and initial work has been done in the Model to apply that, but it's not fully realized yet. Discussion for a more granular approach will be presented in another PR.

Schema API

---

schematics/types/base.py
tests/test_types.py

This is the same as #434, except compatible with the `development` branch.
Fixes #433, closes #434.

Support all non-string Iterables as choices (dev branch)

---

schematics/iteration.py

Try to avoid unnecessary dict conversions in most frequently called method of Schematics.
Simple benchmark is here: https://gist.github.com/vovanbo/dbb3044b417bcd407a4411119aacf415

Atoms iterator performance improvement

---

schematics/compat.py
schematics/datastructures.py
schematics/deprecated.py
schematics/exceptions.py
schematics/models.py
schematics/role.py
schematics/validate.py
tests/test_conversion.py
tests/test_datastructures.py
tests/test_exceptions.py

This PR attempts to address a few issues around exceptions:
#452: all exceptions are now hashable and immutable
#445: exceptions now have a human readable message, and a to_primitive function is provided to for serialization in markup (e.g. json)
#369: conforms to PEP-352, and normalizes all exceptions to a message and an errors field.
This PR has a backward-incompatible change of FieldErrors no longer being mutable, which I'm amenable to. FieldError.pop() is removed as a result.

Enhancing and addressing some issues around exceptions:

---

schematics/types/base.py
schematics/types/compound.py
tests/test_datetime.py

This is a first pass at the feature discussed in issue #429
Some notes:
- instance variable `NumberType.number_class` has been replaced with class variable `NumberType.native_type`
- as discussed, `PolyModelType.native_type` is None because it can't be known
- as discussed, `TimestampType` always converts to float
- made a slight adjustment to ensure that `GeoPointType` always converts to `list`
Regarding `GeoPointType`, it might be nice for it to be a compound type, so that the data type of its components (`int`) can be inspected.  Also, it's a good demonstration of how schematics is meant to work.
I'm sure there will be some feedback, so let me know.

Allow primitive and native types to be inspected

---

schematics/types/net.py
tests/test_types_net.py

Schematics is an excellent library. 
This PR adds support for MACAddressType.
There are several formats: 
'08:00:2b:01:02:03'
'08-00-2b-01-02-03'
'08002b:010203'
'08002b-010203'
'0800.2b01.0203'
'08002b010203'
All of these formats are well understood by postgres and i stole them from the postgres documentation. 
Schematics can support mac addresses out of the box

Add MACAddressType

---

schematics/iteration.py
tests/test_models.py

There's currently a bug where naming fields of a model after the dictionary methods will raise an incorrect DataError during validation (see unit test or https://github.com/toumorokoshi/transmute-core/issues/20)
Looking at the documentation, the atoms() method shouldn't support anything besides a mapping anyway. This builds off of that assumption, and removes the getattr call.

dictionary-named methods are raising a validation exception

---

schematics/validate.py
tests/test_validation.py

I'd really like to be able to raise DataError from within a `validate_fieldname` method so that for a compound type it can provide a more detailed error message.
For instance;
``` python
class A(Model):
foo = DictType(StringType(required=True, min_length=1), required=True)
bar = IntType(required=True, min_value=10)
@classmethod
def validate_foo(cls, data, value):
errors = {}
if 'key1' not in value:
errors['key1'] = ValidationError('key1 not present')
if 'key2' not in value:
errors['key2'] = ValidationError('key2 not present')
if errors:
raise DataError(errors=errors)
A(
raw_data=dict(
foo=dict(key2="I will validate but foo won't as key1 is missing."),
bar=1
),
validate=True
)
```
Ideally what I'd expect from the above is that the following error structure is raised;
``` python
{
'foo': { …
```

Support for raising DataError inside custom validate_fieldname methods.

---

schematics/types/base.py
schematics/types/compound.py

I've added type hints to constructors of field type classes to suggest IDE the actual type of the object and now PyCharm deduces types of all fields in model objects, even for the nested ones like `model.model_list[0].nested_string` which make auto-completion and refactoring to work much better.
See the screenshot:
Code I've tested it on:
```python
from typing import List, Dict, Union, Tuple
import datetime
from decimal import Decimal
from schematics.models import Model
from schematics.types import StringType, ListType, ModelType, NumberType, IntType, FloatType, DecimalType, \
BooleanType, DateType, DateTimeType, DictType
class TestNestedModel(Model):
nested_string = StringType()
class TestModel(Model):
string = StringType()
boolean = BooleanType()
integer = IntType()
float = FloatType() …
```

Add type hints to constructors of field type classes

---

schematics/types/compound.py
tests/test_polymodeltype.py

Please note this tries to fix this bug: When using `PolyModelType` and you `.validate()` on the parent model the validation was not recursive.

Enable PolyModelType recursive validation

---

schematics/types/base.py
tests/test_types.py

* improved float mocking, which should have resolve #463 
* DecimalType now inherits after NumberType class - beside deduplication it should improve consistency among number types
* added some parametrized tests, including ones for DecimalType which seem to have been untested so far

Minor number types refactor

---

schematics/validate.py
tests/test_models.py

It seems there is a regression between 2.0.0a1 and 2.0.1 regarding fileld validators.
* In 2.0.0a1, field validator functions were called on model validation only when the corresponding field was given a value.
* In 2.0.1 it seems that field validators are called no matter what, and the `data` array passed to the validator function is missing entry for the field it is supposed to validate...
```python
#!/usr/bin/env python
from schematics.models import Model
from schematics.types import StringType
from schematics.exceptions import DataError, ValidationError
class FooBar(Model):
foo = StringType(required=True)
bar = StringType()
def validate_foo(self, data, value):
print '>>>>>> testing foo, data=', data
if data['foo'] and 'foo' not in data['foo']:
raise ValidationError('Illegal value')
if …
```

Do not call field validator if field has not been set

---

schematics/contrib/enum_type.py
tests/test_enum_type.py

This PR adds native Py3 enum type. Main reason is to limit possible values to enumerated ones, while `to_native` returns enum instances not strings.

Add EnumType

---

schematics/types/base.py
tests/test_datetime.py
tests/test_types.py

Implements https://github.com/schematics/schematics/issues/539
Implement a TimeDeltaType matching native`datetime.timedelta` type.
Also simplifies `TimeStampType.to_native` call.

Implement TimedeltaType

---

schematics/types/base.py

Added actual `value` into choices error message. Seems like that It's useful to know what value was passed and caused an exception.
Example:
```python
from schematics import Model
from schematics.types import StringType
class MyModel(Model):
x = StringType(required=True, choices=["a", "b", "c"])
model = MyModel({"x": "d"})
model.validate()
```
Before fix:
`schematics.exceptions.DataError: {"x": ["Value must be one of ['a', 'b', 'c']."]}`
After fix:
`schematics.exceptions.DataError: {"x": ["Value (d) must be one of ['a', 'b', 'c']."]}`
Resolves  #593

 #593: Update error message for incorrect choices field

---

tests/test_validation.py

This PR adds no functionality, it simply expands test coverage.
While troubleshooting something I had a moment of doubt about if schematics was properly doing ModelType validation on nested models inside of DictType orListType containers and since I couldn't find a test for it I decided to write one to cover it -- and everything works as I expected.

Add test coverage for model validation inside Dict/List

---

tests/test_models.py

test_models.py had a typo in the documentation

Fixed typo

---

schematics/validate.py
setup.py

Fixes #602 . Also fixes deprecation warning due to invalid escape sequences in setup.py.

Fix syntax warning over comparison of literals using is.
